name: "Test workflow PR for data"

on:
  workflow_call:

jobs:
  slack-notification:
    name: 'PR informations'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: pass-culture-github-actions/pull-request@main
        id: pr
      - run: echo "${{ steps.pr.outputs.number }}"
      - run: echo "${{ steps.pr.outputs.url }}"
      - run: echo "${{ steps.pr.outputs.title }}"
      - run: echo "fin"
