name: "Initiate workflow"

on:
  push:
    branches:
      - master
      - main
      - "maint/**"
  pull_request:
    branches-ignore:
      - docs

permissions: write-all

jobs:
  ping-data-team-on-slack:
    runs-on: ubuntu-latest
    name: "Ping data team on slack"
    steps:
      - run: echo hello world
      - run: echo ${{github.event.number}}
      - run: echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'
