name: "Initiate workflow"

on:
  push:
    branches:
      - master
      - main
      - "maint/**"
  pull_request:
    branches-ignore:
      - docs

permissions: write-all

jobs:
  ping-data-team-on-slack:
    name: "Ping data team on slack"
    uses: ./.github/workflows/dev_on_workflow_ping_data_team.yml
